### ISSUE TITLE
How to excute?

### ISSUE THREAD

**Issue by measproem** [cslinmiso/LINE-instant-messenger-protocol#1]
I am very new programming, how can i run test your application? Is possible for PHP?

**Comment by ruyaoyao** [comment]
It is just the protocol which tells you the basic communication model of LINE messenger works. 
As far as I know, there's no library for PHP.

**Comment by measproem** [comment]
Thanks your replied, Is possible if we write library in PHP? Any risk?

**Comment by anysz** [comment]
Well, if youre looking for A library. some1 had created it. written on Python. python is the easiest coding languague.
