### ISSUE TITLE
LINE_MAIN

### ISSUE THREAD

**Issue by ii64** [cslinmiso/LINE-instant-messenger-protocol#2]
Why does line_main.thrift code is removed

**Comment by ruyaoyao** [comment]
it is useless.

**Comment by ii64** [comment]
it help so many at curve.ttype .-.

**Comment by ruyaoyao** [comment]
it is in face has same content as line.thrift you must know, plus you could look it up in commits.

**Comment by ii64** [comment]
Thanks, issue fixed
