### ISSUE TITLE
sendChatChecked

### ISSUE THREAD

**Issue by ii64** [cslinmiso/LINE-instant-messenger-protocol#3]
Hi, im a bit confused at
> > `...`
> > `
    void sendChatChecked(`
`        1: i32 seq,`
`        2: string consumer,`
`        3: string lastMessageId) throws(1: TalkException e);
      `
> > `...`

what is consumer mean? user id?
Thanks

**Comment by ruyaoyao** [comment]
I guess it should be yourself, put the uid on it and try. :D

**Comment by ii64** [comment]
solved thanks  :3

**Comment by ruyaoyao** [comment]
@anysz could you please share how did you solve it? thank you!

**Comment by ii64** [comment]
add that piece thrift code to line.thrift then on bash
> > `~ $ thrift --gen py line.thrift`

and then its extract few py files. on TalkService take all def and class that connected to sendChatChecked
simply call the function from curve by
self._client.sendChatChecked(0, uid, lastmsgid)

what i dont know right now is how to make the operation faster
cuz all code on the lib is blocking. 
using multithread got ssl error

**Comment by ruyaoyao** [comment]
So that `consumer` is MID which is yourself.
you could in face using thrift to generate your own java line lib.
All I did was providing a  packaged interface for you to use.
