### ISSUE TITLE
fetching Operation

### ISSUE THREAD

**Issue by ii64** [cslinmiso/LINE-instant-messenger-protocol#4]
which one is better for fetching Operation ? 
This ?
> >     list<Operation> fetchOperations(
> >          2: i64 localRev,
> >          3: i32 count) throws(1: TalkException e);

Or this ?
> >     list<Operation> fetchOps(
> >         2: i64 localRev,
> >         3: i32 count,
> >         4: i64 globalRev,
> >         5: i64 individualRev) throws(1: TalkException e);

on the 2nd code, i got problem on globalRev and individualRev. 
could it Rev on line server? 

Thanks

**Comment by ruyaoyao** [comment]
For now, we are currently using fetchOperations instead of fetchOps.

FYI.

**Comment by ii64** [comment]
FYI. Device client don't use fetchOperations. They use fetchOps

**Comment by ii64** [comment]
Thanks, closed the issue.
