### ISSUE TITLE
New API path???

### ISSUE THREAD

**Issue by ii64** [cslinmiso/LINE-instant-messenger-protocol#5]
Ive did sniff the line chrome client. and i found that its use /S3 and not /S4
when i tried to connect with this client, its say bad protocol :(
i think /S3 is best protocol cuz its used on LINE official client. 

When i was sniff it, i cant view data cuz its on https SSL.

This client had 0.06s on 150mbps server but the Official is 0.002s
So i think /S3 better than /S4
but maybe its had different way to connect with it. 

/S4 = /S3
/P4 = /P3
/LF1
/api/v3/TalkService.do
/Q - cert???
/CPF
http://gd2.line.naver.jp/api/v3p/rs - LOGIN?
http://gd2.line.naver.jp/RS4
nelo2-col.linecorp.com
http://gd2.line.naver.jp/kp/api/v21/keep/
http://gd2.line.naver.jp/mh/api/v30/post/get.json
http://gd2.line.naver.jp/mh/api/v30/post/create.json
http://gd2.line.naver.jp/mh/api/v30/post/list.json
http://gd2.line.naver.jp/mh/api/v30/post/delete.json
http://gd2.line.naver.jp/R
http://gd2.line.naver.jp/200

Thanks

**Comment by ruyaoyao** [comment]
Hi thank you for your effort!
You could always create a pull request to make the amendment. 
Thanks!

**Comment by ii64** [comment]
well its use binary, also i got line@ protocol too :D
its easier than the Official Message API

**Comment by craftalpian** [comment]
How to sniff it ?, i've tried sniffing when sending message, but in wireshark there is no data message i sent. I also have seen tcp stream and udp stream, I just see words that I can not read. Btw ,what is your id line ? So i can ask you :)

**Comment by ii64** [comment]
Sure dude, Line id: <>
If you cant add me, just give yours and ill add it
Btw line@ thrift what I mean is just .so library which can be imported to python.
But im not sure what is the function inside it.

@craftalpian 
Use line client with low secure for sniff the data, for example like' Line Chrome
Also if you look till the googlechrome extension you will found the Line Chrome client engine which is proguarded javascript. cuz if you sniff Line desktop, its need so many setting cause its tcp connection.

I just look down to java cause I think its faster for handshaking
And yea I found much different between all thrift on all platform. Like java, javascript, PHP, python
So I patch the thttpclient python to make it competible with http / 80 which is its dont need handshake
And its works better. Path /S3 + Thrift patch = speed increased

From original 0.07 - /S4 with https 
To 0.007 - /S3 with http

And, I cant got 0.002 cuz geolocation problem.
The possible speed rightnow is 0.004
I thanks to some lib, its can reuse the existed connection, no need to open again,
The point' is 
/S4 use Compact Protocol
/S3 use Binary Protocol

Is anyone did sniffing for line@ ?
I just want to use line@ protocol instead of MessageAPI.
Which it will be easier, and no need webhook. Easy to manage.

Thanks everyone.

**Comment by fadliansyah153** [comment]
hi sir ,plis help me edit thrift ,me need speed 0.004

**Comment by lintangtimur** [comment]
hello, @anysz . can u explain this "if you sniff Line desktop, its need so many setting cause its tcp connection." are you can sniff Line desktop with wireshark?

can u sniff LINE from mobile devices?
