### ISSUE TITLE
thrift compiling has an error

### ISSUE THREAD

**Issue by NabiKAZ** [cslinmiso/LINE-instant-messenger-protocol#6]
Do you can help me about this error:
```
# thrift --gen php line.thrift
[ERROR:/thrift/line.thrift:1002] (last token was 'from')
Cannot use reserved language keyword: "from"
```

**Comment by ruyaoyao** [comment]
try to generate it with thrift version below 0.9.3 or you could rename parameter name `from` to something else since `from` is a reserved keyword in Python.

**Comment by NabiKAZ** [comment]
Thanks, I rename `from` and resolve it.
