### ISSUE TITLE
This script its work?

### ISSUE THREAD

**Issue by Alnyz** [cslinmiso/LINE-instant-messenger-protocol#8]
im so interested about this [tools](https://github.com/cslinmiso/LINE-instant-messenger-protocol/tree/master/tools), but i dont know what `path` meant for this [part](https://github.com/cslinmiso/LINE-instant-messenger-protocol/blob/5063f795a2798b1663e25dd52fcc1cbbf49764b1/tools/view-android-settings.py#L116)

**Comment by ruyaoyao** [comment]
as in file path.
